--Завдання 1
SELECT DISTINCT MFR FROM ORDERS INNER JOIN CUSTOMERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM 
WHERE YEAR(ORDERS.ORDER_DATE) = 2008 AND CUSTOMERS.COMPANY LIKE '%Corp%';

--Завдання 2
SELECT CUST_NUM, MONTH(ORDER_DATE) AS OrderMonth, COUNT(DISTINCT ORDERS.ORDER_NUM) AS UniqueOrders FROM CUSTOMERS
LEFT OUTER JOIN ORDERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM
WHERE YEAR(ORDERS.ORDER_DATE) = 2008 AND CUSTOMERS.COMPANY LIKE '%Corp%'
GROUP BY CUSTOMERS.CUST_NUM, MONTH(ORDER_DATE)
ORDER BY UniqueOrders DESC;

--Завдання 3 
SELECT DISTINCT CUST_NUM, UPPER(COMPANY) AS CompanyName, PRODUCTS.DESCRIPTION FROM CUSTOMERS
LEFT OUTER JOIN ORDERS ON ORDERS.CUST = CUSTOMERS.CUST_NUM
LEFT OUTER JOIN PRODUCTS ON PRODUCTS.MFR_ID = ORDERS.MFR
WHERE YEAR(ORDERS.ORDER_DATE) = 2008 AND CUSTOMERS.COMPANY LIKE '%Corp%';