USE [test];

GO 
CREATE SCHEMA DROBCHAK;

CREATE TABLE DROBCHAK.DATATYPES (
ID BIGINT, 
AGE TINYINT
);

INSERT INTO DROBCHAK.DATATYPES(ID, AGE)
VALUES(10000, 22);

INSERT INTO DROBCHAK.DATATYPES(ID, AGE)
VALUES(10001, 32);

-- Implicit data type conversion

INSERT INTO DROBCHAK.DATATYPES(ID, AGE)
VALUES('10002', 32);

-- Implicit data type conversion

INSERT INTO DROBCHAK.DATATYPES(ID, AGE)
VALUES('10003', '35');

-- Implicit data type conversion

INSERT INTO DROBCHAK.DATATYPES(ID, AGE)
VALUES('19700', '35');

UPDATE DROBCHAK.DATATYPES SET ID = 19711 WHERE ID = '19700101'

SELECT *
FROM DROBCHAK.DATATYPES;

