--Завдання 1
SELECT EMPL_NUM, NAME, TITLE, AGE FROM SALESREPS WHERE AGE>45 ORDER BY AGE DESC; 
--Завдання 2
SELECT DISTINCT MFR, PRODUCT FROM ORDERS WHERE YEAR(order_date)=2008;
--Завдання 3
SELECT TOP 1 WITH TIES REP, COUNT(*) AS [ORDER QTY] FROM ORDERS WHERE YEAR(order_date) = 2008 GROUP BY REP ORDER BY [ORDER QTY] DESC;